# Generated by Django 5.2.1 on 2025-05-31 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_property_stripe_subscription_id'),
        ('memberships', '0008_servicepackage_stripe_product_id_and_more'),
        ('staff_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.property'),
        ),
        migrations.AlterField(
            model_name='job',
            name='service_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='memberships.serviceagreement'),
        ),
    ]
