# Generated by Django 5.2.1 on 2025-06-02 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_portal', '0003_staffrouteassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffrouteassignment',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterField(
            model_name='staffrouteassignment',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff_portal.route'),
        ),
        migrations.AlterUniqueTogether(
            name='staffrouteassignment',
            unique_together={('staff', 'route', 'start_date', 'end_date', 'shift_type')},
        ),
        migrations.CreateModel(
            name='JobFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='staff_portal.job')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
