# Generated by Django 5.2.1 on 2025-06-13 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_requests', '0003_alter_quoterequest_photo'),
        ('staff_portal', '0004_alter_staffrouteassignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='quote_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='quote_requests.quoterequest'),
        ),
    ]
