# Generated by Django 5.2.1 on 2025-06-23 18:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_portal', '0005_job_quote_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffrouteassignment',
            unique_together={('staff', 'route', 'start_date', 'end_date')},
        ),
        migrations.RemoveField(
            model_name='staffrouteassignment',
            name='shift_type',
        ),
    ]
