# Generated by Django 5.2.1 on 2025-05-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='route_number',
            field=models.PositiveIntegerField(blank=True, help_text='Route number for staff', null=True),
        ),
    ]
