# Generated by Django 5.2.1 on 2025-05-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_route_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='route_number',
        ),
        migrations.AddField(
            model_name='property',
            name='route_number',
            field=models.PositiveIntegerField(blank=True, help_text='Route number for staff', null=True),
        ),
    ]
