# Generated by Django 5.2.1 on 2025-05-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_profile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='has_active_service',
            field=models.BooleanField(default=False, help_text='Does this property currently have an active service plan?'),
        ),
    ]
