# Generated by Django 5.2.1 on 2025-05-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_property_has_active_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe Subscription ID if this property has an active service.', max_length=255, null=True, unique=True),
        ),
    ]
