# Generated by Django 5.2.1 on 2025-06-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_property_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='marketing_consent',
            field=models.BooleanField(default=False, help_text='User has opted in to marketing emails'),
        ),
    ]
