# Generated by Django 5.2.1 on 2025-05-24 08:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('B2B', 'Border 2 Border'), ('SPLASH', 'SplashZone Pools')], max_length=10)),
                ('tier', models.CharField(choices=[('SILVER', 'Silver'), ('GOLD', 'Gold')], max_length=10)),
                ('description', ckeditor.fields.RichTextField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
