# Generated by Django 5.2.1 on 2025-05-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_servicepackage_stripe_price_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepackage',
            name='category',
            field=models.CharField(choices=[('B2B', 'Border 2 Border'), ('SZP', 'Splash Zone Pools'), ('DSP', 'DS Property Management')], max_length=10),
        ),
    ]
