# Generated by Django 5.2.1 on 2025-05-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_alter_servicepackage_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepackage',
            name='tier',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double')], max_length=10),
        ),
    ]
