# Generated by Django 5.2.1 on 2025-05-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_serviceagreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceagreement',
            name='end_date',
            field=models.DateField(blank=True, help_text='Date service agreement ended/cancelled', null=True),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe Subscription ID associated with this agreement.', max_length=255, null=True, unique=True),
        ),
    ]
