# Generated by Django 5.2.1 on 2025-05-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0007_serviceagreement_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='Stripe Product ID associated with this package.', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Stripe Price ID associated with this package.', max_length=100, null=True, unique=True),
        ),
    ]
