# Generated by Django 5.2.1 on 2025-06-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote_requests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoterequest',
            old_name='created_at',
            new_name='submitted_at',
        ),
    ]
