# Generated by Django 5.2.1 on 2025-06-13 10:31

import quote_requests.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_requests', '0002_rename_created_at_quoterequest_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='photo',
            field=models.ImageField(storage=quote_requests.storage_backends.QuoteImageStorage(), upload_to='requests/'),
        ),
    ]
