# Generated by Django 5.2.1 on 2025-06-16 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_property_stripe_subscription_id'),
        ('quote_requests', '0005_quoterequest_tax_percent_quoterequest_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='related_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.property'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
