# Generated by Django 5.2.1 on 2025-06-18 10:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_requests', '0006_quoterequest_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='response_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, blank=True),
        ),
    ]
