# Generated by Django 5.2.1 on 2025-06-18 10:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_requests', '0008_populate_response_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='response_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
