# Generated by Django 5.2.1 on 2025-06-22 13:40

import quote_requests.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_requests', '0009_alter_quoterequest_response_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=quote_requests.storage_backends.QuoteImageStorage(), upload_to='requests/'),
        ),
    ]
